###
# Requisicao GET para listar todos
GET http://localhost:8080/

###
# Requisicao GET para listar detalhes de 1 registro
GET http://localhost:8080/detalhes/3

###
# Requisição POST para cadastrar um novo contato
POST http://localhost:8080/adicionar
Content-Type: application/json

{
    "nome": "Asdrubal",
    "tipo": "Residencial",
    "telefone": "5555-2222"
}

###
# Requisição POST para editar um contato
POST http://localhost:8080/adicionar
Content-Type: application/json

{
    "id": 3,
    "nome": "Clotilde",
    "tipo": "Residencial",
    "telefone": "3333-3332"
}

###
# Requisição GET para deletar um contato
GET http://localhost:8080/deletar/1

